### PR TITLE
Fix panic on buggy kustomization, add retries

### LINKED ISSUE #208: [BUG] Kustomizer makes Microshift to crash if manifest is not validated
#### What happened:

Adding a set of buggy manifests to `/var/lib/microshift/manifests/` and its kustomization.yaml provokes Microshift to crash.

#### What you expected to happen:

If a manifests has any error, don't apply it, but microshift should keep up and running. 

#### How to reproduce it (as minimally and precisely as possible):

1. Create a kustomization.yaml with one resource (i.e. pod.yaml)
2. Pod.yaml must be buggy, and `oc apply -f pod.yaml` should not work.

#### Environment:
- Microshift Version: 4.7.0-0.microshift-2021-08-10-163759
- Hardware configuration: Libvirt VM 2GB/2vCPUs
- OS (e.g: `cat /etc/os-release`): 
- cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"

- Kernel (e.g. `uname -a`): Linux localhost.localdomain 4.18.0-305.10.2.el8_4.x86_64 #1 SMP Mon Jul 12 04:43:18 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

- Others:

#### Relevant Logs 

```
Aug 12 11:23:39 localhost.localdomain microshift[7840]: error: rawResources failed to read Resources: YAML file [klusterlet-kubeconfighub.yaml] encounters a format error.
Aug 12 11:23:39 localhost.localdomain microshift[7840]: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".kubeconfig":interface {}(nil)}
Aug 12 11:23:39 localhost.localdomain systemd[1]: microshift.service: Main process exited, code=exited, status=1/FAILURE
Aug 12 11:23:39 localhost.localdomain systemd[1]: microshift.service: Failed with result 'exit-code'.

```

### PR DESCRIPTION
**Pull request by fzdarsky**
Signed-off-by: Frank A. Zdarsky <fzdarsky@redhat.com>

Closes #208

### CODE REVIEW

File: pkg/kustomize/apply.go [hunk 1]
```diff
@@ -41,21 +46,35 @@ func (s *Kustomizer) Run(ctx context.Context, ready chan<- struct{}, stopped cha
...
 		logrus.Infof("No kustomization found at " + kustomization)
 	}
 
 	return ctx.Err()
 }
 
-func ApplyKustomization(path string, kubeconfig string) error {
+func ApplyKustomizationWithRetries(kustomization string, kubeconfig string) error {
+	err := ApplyKustomization(kustomization, kubeconfig)
+	for retry := 1; retry <= retries && err != nil; retry++ {
```
Comment (rootfs) [inline pkg/kustomize/apply.go:63]: how about reusing `wait.poll()` as in [here](https://github.com/redhat-et/microshift/blob/main/pkg/assets/crd.go#L58)

Comment (fzdarsky) [reply pkg/kustomize/apply.go]: Good idea, thank you!
